volumes:
  db:
  artifacts:

services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pw
      POSTGRES_DB: goosebit
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U db_user -d goosebit
      interval: 4s
      timeout: 2s

  goosebit:
    image: upstreamdata/goosebit
    environment:
      GOOSEBIT_DB_URI: postgres://db_user:db_pw@postgres:5432/goosebit
      GOOSEBIT_SECRET_KEY: 1a7090da4fbe9c72f888a4772302eac3
      GOOSEBIT_ARTIFACTS_DIR: /artifacts
      FORWARDED_ALLOW_IPS: "*"
      GOOSEBIT_LOGGING__VERSION: 1
      GOOSEBIT_LOGGING__ROOT__LEVEL: DEBUG
      GOOSEBIT_LOGGING__HANDLERS__CONSOLE__LEVEL: DEBUG
      GOOSEBIT_LOGGING__HANDLERS__CONSOLE__CLASS: logging.StreamHandler
      GOOSEBIT_LOGGING__ROOT__HANDLERS: '["console"]'
    volumes:
      - artifacts:/artifacts
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/certs:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - goosebit
